version: '3.9'

networks:
    authmantle_net:

services:
    authmantle-db:
        container_name: "authmantle_db"
        image: postgres:14
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 5s
        networks:
            - authmantle_net
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: "authmantledb"
            POSTGRES_PASSWORD: "dudde"
        volumes:
            - .\.db\init.sql:/docker-entrypoint-initdb.d/creation.sql
            - .\.db\inserts.sql:/inserts.sql
            #- .\.db\data\:/var/lib/postgresql/data