version: '3.9'

networks:
    authmantle_net:

services:
    authmantle-db:
        container_name: "authmantle_db"
        image: postgres:14
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
            interval: 10s
            timeout: 10s
            retries: 5
            start_period: 5s
        networks:
            - authmantle_net
        ports:
            - "5432:5432"
        environment:
            TZ: 'Europe/Stockholm'
            POSTGRES_DB: "authmantledb"
            POSTGRES_PASSWORD: "dudde"
        volumes:
            - .\.db\init.sql:/docker-entrypoint-initdb.d/creation.sql
            - .\.db\inserts.sql:/inserts.sql
            #- .\.db\data\:/var/lib/postgresql/data
    authmantle-api:
        container_name: "authmantle_api"
        image: authmantle-api
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            authmantle-db:
                condition: service_started
        links:
            - authmantle-db
        networks:
            - authmantle_net
        mem_reservation: 50m
        mem_limit: 50m
        ports:
            - "8443:8443"