INSERT INTO authmantledb.us_country (
    id,
    country_name,
    country_alpha_name,
    region_name,
    region_alpha_name,
    updated_at,
    updated_by,
    registered_at,
    registered_by
)
VALUES
    (nextval('us_country_id_seq'), 'Afghanistan', 'AF', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Albania', 'AL', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Algeria', 'DZ', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Andorra', 'AD', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Angola', 'AO', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Antigua and Barbuda', 'AG', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Argentina', 'AR', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Armenia', 'AM', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Australia', 'AU', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Austria', 'AT', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Azerbaijan', 'AZ', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Bahamas', 'BS', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Bahrain', 'BH', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Bangladesh', 'BD', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Barbados', 'BB', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Belarus', 'BY', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Belgium', 'BE', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Belize', 'BZ', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Benin', 'BJ', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Bhutan', 'BT', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Bolivia', 'BO', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Bosnia and Herzegovina', 'BA', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Botswana', 'BW', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Brazil', 'BR', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Brunei', 'BN', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Bulgaria', 'BG', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Burkina Faso', 'BF', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Burundi', 'BI', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Cabo Verde', 'CV', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Cambodia', 'KH', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Cameroon', 'CM', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Canada', 'CA', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Central African Republic', 'CF', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Chad', 'TD', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Chile', 'CL', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'China', 'CN', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Colombia', 'CO', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Comoros', 'KM', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Congo, Democratic Republic of the', 'CD', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Congo, Republic of the', 'CG', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Costa Rica', 'CR', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Cote d''Ivoire', 'CI', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Croatia', 'HR', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Cuba', 'CU', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Cyprus', 'CY', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Czech Republic', 'CZ', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Denmark', 'DK', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Djibouti', 'DJ', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Dominica', 'DM', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Dominican Republic', 'DO', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Ecuador', 'EC', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Egypt', 'EG', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'El Salvador', 'SV', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Equatorial Guinea', 'GQ', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Eritrea', 'ER', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Estonia', 'EE', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Eswatini', 'SZ', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Ethiopia', 'ET', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Fiji', 'FJ', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Finland', 'FI', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'France', 'FR', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Gabon', 'GA', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Gambia', 'GM', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Georgia', 'GE', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Germany', 'DE', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Ghana', 'GH', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Greece', 'GR', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Grenada', 'GD', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Guatemala', 'GT', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Guinea', 'GN', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Guinea-Bissau', 'GW', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Guyana', 'GY', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Haiti', 'HT', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Honduras', 'HN', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Hong Kong', 'HK', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Hungary', 'HU', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Iceland', 'IS', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'India', 'IN', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Indonesia', 'ID', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Iran', 'IR', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Iraq', 'IQ', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Ireland', 'IE', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Israel', 'IL', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Italy', 'IT', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Jamaica', 'JM', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Japan', 'JP', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Jordan', 'JO', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Kazakhstan', 'KZ', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Kenya', 'KE', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Kiribati', 'KI', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Kosovo', 'XK', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Kuwait', 'KW', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Kyrgyzstan', 'KG', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Laos', 'LA', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Latvia', 'LV', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Lebanon', 'LB', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Lesotho', 'LS', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Liberia', 'LR', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Libya', 'LY', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Liechtenstein', 'LI', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Lithuania', 'LT', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Luxembourg', 'LU', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Madagascar', 'MG', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Malawi', 'MW', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Malaysia', 'MY', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Maldives', 'MV', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Mali', 'ML', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Malta', 'MT', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Marshall Islands', 'MH', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Mauritania', 'MR', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Mauritius', 'MU', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Mexico', 'MX', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Micronesia, Federated States of', 'FM', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Moldova', 'MD', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Monaco', 'MC', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Mongolia', 'MN', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Montenegro', 'ME', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Morocco', 'MA', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Mozambique', 'MZ', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Myanmar (Burma)', 'MM', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Namibia', 'NA', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Nauru', 'NR', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Nepal', 'NP', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Netherlands', 'NL', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'New Zealand', 'NZ', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Nicaragua', 'NI', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Niger', 'NE', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Nigeria', 'NG', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'North Korea', 'KP', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'North Macedonia', 'MK', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Norway', 'NO', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Oman', 'OM', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Pakistan', 'PK', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Palau', 'PW', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Panama', 'PA', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Papua New Guinea', 'PG', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Paraguay', 'PY', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Peru', 'PE', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Philippines', 'PH', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Poland', 'PL', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Portugal', 'PT', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Qatar', 'QA', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Romania', 'RO', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Russia', 'RU', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Rwanda', 'RW', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Saint Kitts and Nevis', 'KN', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Saint Lucia', 'LC', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Saint Vincent and the Grenadines', 'VC', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Samoa', 'WS', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'San Marino', 'SM', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Sao Tome and Principe', 'ST', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Saudi Arabia', 'SA', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Senegal', 'SN', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Serbia', 'RS', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Seychelles', 'SC', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Sierra Leone', 'SL', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Singapore', 'SG', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Slovakia', 'SK', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Slovenia', 'SI', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Solomon Islands', 'SB', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Somalia', 'SO', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'South Africa', 'ZA', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'South Korea', 'KR', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'South Sudan', 'SS', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Spain', 'ES', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Sri Lanka', 'LK', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Sudan', 'SD', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Suriname', 'SR', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Sweden', 'SE', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Switzerland', 'CH', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Syria', 'SY', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Taiwan', 'TW', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Tajikistan', 'TJ', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Tanzania', 'TZ', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Thailand', 'TH', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Timor-Leste', 'TL', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Togo', 'TG', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Tonga', 'TO', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Trinidad and Tobago', 'TT', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Tunisia', 'TN', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Turkey', 'TR', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Turkmenistan', 'TM', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Tuvalu', 'TV', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Uganda', 'UG', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Ukraine', 'UA', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'United Arab Emirates', 'AE', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'United Kingdom', 'GB', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'United States', 'US', 'North America', 'NA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Uruguay', 'UY', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Uzbekistan', 'UZ', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Vanuatu', 'VU', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Vatican City', 'VA', 'Europe', 'EU', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Venezuela', 'VE', 'South America', 'SA', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Vietnam', 'VN', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Wallis and Futuna', 'WF', 'Oceania', 'OC', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Western Sahara', 'EH', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Yemen', 'YE', 'Asia', 'AS', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Zambia', 'ZM', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_country_id_seq'), 'Zimbabwe', 'ZW', 'Africa', 'AF', NOW(), 'default_SQL', NOW(), 'default_SQL');

INSERT INTO authmantledb.us_role (
    id,
    role_name,
    role_description,
    updated_at,
    updated_by,
    registered_at,
    registered_by
)
VALUES
    (nextval('us_role_id_seq'), 'admin', 'Administrator', NOW(), 'default_SQL', NOW(), 'default_SQL'),
    (nextval('us_role_id_seq'), 'user', 'User', NOW(), 'default_SQL', NOW(), 'default_SQL');

-- remove later -- is essentially invalid
INSERT INTO authmantledb.in_supp_auth_audience (id,audience_name)
VALUES (nextval('in_supp_auth_audience_id_seq'),'https://some-website.dudde.com');
INSERT INTO authmantledb.in_supp_auth_allowed_redirects (id,redirect_uri)
VALUES (nextval('in_supp_auth_allowed_redirects_id_seq'), 'http://localhost:3000');
-- remove later

INSERT INTO authmantledb.in_supp_auth_grant_types (id,grant_type_name)
VALUES (nextval('in_supp_auth_grant_types_id_seq'),'authorization_code');

INSERT INTO authmantledb.in_supp_auth_scopes (id,scope_name)
VALUES (nextval('in_supp_auth_scopes_id_seq'),'openid'),
       (nextval('in_supp_auth_scopes_id_seq'),'profile'),
       (nextval('in_supp_auth_scopes_id_seq'),'email');

INSERT INTO authmantledb.in_supp_auth_claims (id,claim_name)
VALUES (nextval('in_supp_auth_claims_id_seq'),'sub'),
       (nextval('in_supp_auth_claims_id_seq'),'iss'),
       (nextval('in_supp_auth_claims_id_seq'),'email'),
       (nextval('in_supp_auth_claims_id_seq'),'profile');

INSERT INTO authmantledb.in_supp_auth_subject_types (id,subject_type_name)
VALUES (nextval('in_supp_auth_subject_types_id_seq'),'public');


-- test admin user (remove later)
insert into authmantledb.us_user (
    id,
    username,
    role_id,
    email,
    "password",
    first_name,
    last_name,
    phone_number,
    city,
    state,
    country_id,
    share_id,
    updated_at,
    updated_by,
    registered_at,
    registered_by
)
values
(
    nextval('us_user_id_seq'),
    'admin',
    1,
    'admin@dudde.com',
    'a$$word',
    'Admin',
    '',
    '0725112233',
    'Aurora',
    'Colorado',
    188,
    null,
    NOW(),
    'default_SQL',
    NOW(),
    'default_SQL'
),
(
    nextval('us_user_id_seq'),
    'boijec',
    currval('us_role_id_seq'),
    'user@dudde.com',
    'a$$word',
    'Carl',
    'Boije',
    '0725112233',
    'Aurora',
    'Colorado',
    188,
    null,
    NOW(),
    'default_SQL',
    NOW(),
    'default_SQL'
);